language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/SDM630/SDM630.ino
    - CPPLINT=true

install:
    - pip install -U platformio
    - pip install -U cpplint
    - platformio lib -g install file://.

script:
    - if [[ "$CPPLINT" ]]; then cpplint --repository=. --recursive --linelength=200 --filter=-build/include ./src; else platformio ci --lib="." --board=lolin32; fi

notifications:
  email:
    on_success: change
    on_failure: change